<a href="https://colab.research.google.com/github/PrateekCoder/lets_data_science/blob/main/Demystifying_Naive_Bayes_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import Required Packages

In [1]:
# Importing necessary libraries
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

## Load the Dataset

In [2]:
# Loading the Iris dataset
iris = datasets.load_iris()

# Converting the dataset into a DataFrame
iris_df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])

# Displaying the first 5 rows of the DataFrame
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

## Preparing the Dataset

In [3]:
# Preparing the data
X = iris.data
y = iris.target

# Splitting the data - 70% training, 30% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

## Training the Model

In [4]:
# Training the model
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

## Making Prediction

In [5]:
# Making predictions
y_pred = gnb.predict(X_test)

## Evaluating the Model

In [6]:
# Evaluating the model
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

# Confusion Matrix
print("\nConfusion Matrix:\n", metrics.confusion_matrix(y_test, y_pred))

# Classification Report
print("\nClassification Report:\n", metrics.classification_report(y_test, y_pred))

Accuracy: 0.9333333333333333

Confusion Matrix:
 [[14  0  0]
 [ 0 16  2]
 [ 0  1 12]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.89      0.91        18
           2       0.86      0.92      0.89        13

    accuracy                           0.93        45
   macro avg       0.93      0.94      0.93        45
weighted avg       0.94      0.93      0.93        45

